# Generated by Django 2.1 on 2018-08-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=20000)),
                ('writedate', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField()),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('joindate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('fname', models.ImageField(blank=True, upload_to='kmweb/%Y/%m/%d')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
    ]
