# Generated by Django 2.1 on 2018-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='memo',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=10000)),
                ('writedate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'memo',
            },
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
